extends Node

func _init() -> void:
	var icon_overwrite1 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/absorption_field_generator.png")
	icon_overwrite1.take_over_path("res://content/icons/absorption_field_generator.png")
	var icon_overwrite2 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/absorption_hull.png")
	icon_overwrite2.take_over_path("res://content/icons/absorption_hull.png")
	var icon_overwrite3 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/coated_lens.png")
	icon_overwrite3.take_over_path("res://content/icons/coated_lens.png")
	var icon_overwrite4 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/coil_grid.png")
	icon_overwrite4.take_over_path("res://content/icons/coil_grid.png")
	var icon_overwrite5 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/crafting1.png")
	icon_overwrite5.take_over_path("res://content/icons/crafting1.png")
	var icon_overwrite6 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/cryo_magnet_rail_system.png")
	icon_overwrite6.take_over_path("res://content/icons/cryo_magnet_rail_system.png")
	var icon_overwrite7 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/crystalic_filter.png")
	icon_overwrite7.take_over_path("res://content/icons/crystalic_filter.png")
	var icon_overwrite8 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/dampener_ring.png")
	icon_overwrite8.take_over_path("res://content/icons/dampener_ring.png")
	var icon_overwrite9 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/data_matrix.png")
	icon_overwrite9.take_over_path("res://content/icons/data_matrix.png")
	var icon_overwrite10 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/dynamic_dampener.png")
	icon_overwrite10.take_over_path("res://content/icons/dynamic_dampener.png")
	var icon_overwrite11 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/energy_casing.png")
	icon_overwrite11.take_over_path("res://content/icons/energy_casing.png")
	var icon_overwrite12 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/feedback_buffer.png")
	icon_overwrite12.take_over_path("res://content/icons/feedback_buffer.png")
	var icon_overwrite13 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/fusion_cell.png")
	icon_overwrite13.take_over_path("res://content/icons/fusion_cell.png")
	var icon_overwrite14 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/lens_array.png")
	icon_overwrite14.take_over_path("res://content/icons/lens_array.png")
	var icon_overwrite15 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/liquefier.png")
	icon_overwrite15.take_over_path("res://content/icons/liquefier.png")
	var icon_overwrite16 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/magnetic_rail_system.png")
	icon_overwrite16.take_over_path("res://content/icons/magnetic_rail_system.png")
	var icon_overwrite17 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/magnetic_screws.png")
	icon_overwrite17.take_over_path("res://content/icons/magnetic_screws.png")
	var icon_overwrite18 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/micro_gear.png")
	icon_overwrite18.take_over_path("res://content/icons/micro_gear.png")
	var icon_overwrite19 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/modular_beam_emitter.png")
	icon_overwrite19.take_over_path("res://content/icons/modular_beam_emitter.png")
	var icon_overwrite20 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/modular_pulse_emitter.png")
	icon_overwrite20.take_over_path("res://content/icons/modular_pulse_emitter.png")
	var icon_overwrite21 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/nano_circuit_board.png")
	icon_overwrite21.take_over_path("res://content/icons/nano_circuit_board.png")
	var icon_overwrite22 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/overload_buffer.png")
	icon_overwrite22.take_over_path("res://content/icons/overload_buffer.png")
	var icon_overwrite23 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/phase_coil.png")
	icon_overwrite23.take_over_path("res://content/icons/phase_coil.png")
	var icon_overwrite24 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/pivot_mechanism.png")
	icon_overwrite24.take_over_path("res://content/icons/pivot_mechanism.png")
	var icon_overwrite25 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/plasma_cell.png")
	icon_overwrite25.take_over_path("res://content/icons/plasma_cell.png")
	var icon_overwrite26 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/pulse_emitter.png")
	icon_overwrite26.take_over_path("res://content/icons/pulse_emitter.png")
	var icon_overwrite27 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/rail_track.png")
	icon_overwrite27.take_over_path("res://content/icons/rail_track.png")
	var icon_overwrite28 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/ruby_coated_lens.png")
	icon_overwrite28.take_over_path("res://content/icons/ruby_coated_lens.png")
	var icon_overwrite29 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/servo_drive.png")
	icon_overwrite29.take_over_path("res://content/icons/servo_drive.png")
	var icon_overwrite30 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/servo_motor.png")
	icon_overwrite30.take_over_path("res://content/icons/servo_motor.png")
	var icon_overwrite31 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/sintered_metal.png")
	icon_overwrite31.take_over_path("res://content/icons/sintered_metal.png")
	var icon_overwrite32 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/vacuum_energy_cell.png")
	icon_overwrite32.take_over_path("res://content/icons/vacuum_energy_cell.png")
	var icon_overwrite33 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/crafting2.png")
	icon_overwrite33.take_over_path("res://content/icons/crafting2.png")
	var icon_overwrite34 := preload("res://mods-unpacked/Team2-MoreToMine/overwrites/content/icons/crafting3.png")
	icon_overwrite34.take_over_path("res://content/icons/crafting3.png")
